export const en = {
  locale: "en",
  htmlLang: "en",
  path: "/en",

  meta: {
    title: "VIA — Strategy that takes shape",
    description:
      "Strategy, brand, marketing, sales, and technology connected to build businesses in motion.",
    ogImageAlt: "VIA — strategy that takes shape.",
  },

  skipLinkLabel: "Skip to content",

  organization: {
    availableLanguage: ["en"],
  },

  header: {
    logoLabel: "VIA, home",
    navAriaLabel: "Main navigation",
    navCompactAriaLabel: "Main navigation, compact version",
    nav: [
      { id: "fazemos", label: "What we do" },
      { id: "moikato", label: "Moikato" },
      { id: "trabalhos", label: "Work" },
      { id: "contato", label: "Contact" },
    ],
    ctaLabel: "Talk to VIA",
    menuAriaLabel: "Menu",
    openMenuLabel: "Open menu",
    closeMenuLabel: "Close menu",
    menuContactNote: "Have a project in mind?",
    menuContactLabel: "Talk to VIA",
    langSwitch: {
      groupAriaLabel: "Language",
      current: "EN",
      other: "PT",
      otherHtmlLang: "pt-BR",
      href: "/",
      ariaLabel: "View the site in Portuguese",
    },
  },

  hero: {
    kicker: "VIA / GROWTH COMPANY",
    headlineAriaLabel: "VIA — strategy that takes shape.",
    headlineLead: "Strategy that ",
    headlineHighlight: "takes shape.",
    ctaNote: "Have a project in mind?",
    ctaLabel: "Let's talk",
    secondaryCtaLabel: "Meet VIA",
  },

  coverflow: {
    assistiveTitle: "Projects that took shape.",
    regionRoleDescription: "carousel",
    regionLabel: "VIA's projects",
    prevLabel: "Previous project",
    nextLabel: "Next project",
    selectLabelPrefix: "Select project",
    slideLabelProjectWord: "Project",
    slideLabelOfWord: "of",
    byVia: "VIA PROJECT",
    gestureHint: "Swipe, use the side scroll, or the arrow keys.",
    beforeAfter: {
      beforeLabel: "Before",
      afterLabel: "After",
      valueTextSuffix: "of the new identity visible",
    },
    health: {
      statement: "Care that changes lives.",
      disciplines: ["Strategy", "Content", "Media"],
      alertLabel: "New appointment",
      ticketTitle: "Appointment confirmed",
      ticketMeta: "Vitae · Cardiology",
      ticketDay: "Tuesday, 2pm",
      ticketMode: "In person",
    },
  },

  capabilities: {
    kicker: "FROM IDEA TO OPERATION",
    title: "VIA thinks and builds.",
    description:
      "Strategy and execution move together, turning ideas into brands, experiences, and real growth.",
    previewAriaPrefix: "See",
    previewAriaMiddle: "as an example of",
    items: [
      {
        accent: "purple",
        icon: "marca",
        title: "Brand & identity",
        text: "Positioning, naming, logo, and a visual system that holds the brand together.",
        reference: {
          client: "In Tha Route",
          href: "#case-in-tha-route",
          image: "/projects/route-primary.webp",
          position: "right center",
          fit: "contain",
        },
      },
      {
        accent: "blue",
        icon: "site",
        title: "Websites & landing pages",
        text: "Digital experiences that present, guide, and convert.",
        reference: {
          client: "A Tardinha",
          href: "#case-tardinha",
          image: "/tardinha.webp",
          position: "center",
          fit: "contain",
        },
      },
      {
        accent: "cyan",
        icon: "conteudo",
        title: "Content & campaigns",
        text: "Social media, channel management, scripts, and campaigns with creative direction.",
        reference: {
          client: "Visual content",
          href: "#case-conteudo-visual",
          image: "/projects/latino-beats.webp",
          position: "center 34%",
        },
      },
      {
        accent: "green",
        icon: "trafego",
        title: "Traffic & performance",
        text: "Organic and paid growth, read, learned from, and turned into the next move.",
        reference: {
          client: "Healthcare clinics",
          href: "#case-saude",
        },
      },
      {
        accent: "blue",
        icon: "estrategia",
        title: "Strategy & sales",
        text: "Offer and process connected to turn demand into revenue.",
        reference: {
          client: "Moikato",
          href: "#case-moikato",
          image: "/projects/moikato-brand.webp",
          position: "center",
          fit: "contain",
        },
      },
      {
        accent: "cyan",
        icon: "tecnologia",
        title: "Technology & automation",
        text: "Websites, CRM, automation, and AI applied to the business.",
        reference: {
          client: "Moikato",
          href: "#case-moikato",
          image: "/via-moikato-london.webp",
          position: "center 38%",
        },
      },
    ],
  },

  system: {
    videoAriaLabel: "Video testimonial from Samuel, of Moikato, about VIA's work",
    videoFallback: "Your browser can't play this video.",
    videoBadge: "REAL TESTIMONIAL · LONDON",
    quoteKicker: "RESULTS, FIRST-HAND",
    quote: "“They believed in my work.”",
    quoteAttribution: "Samuel · Moikato · Entrepreneur in London",
    caseKicker: "CASE STUDY / MOIKATO / BRAZIL → UK",
    title: "A Brazilian story, told by the person living it.",
    description:
      "Moikato grew from Brazil into the UK. VIA connected origin, brand, and digital experience to keep pace with that move.",
    storyAriaLabel: "The project's story in three moments",
    story: [
      {
        step: "01 · ORIGIN",
        title: "Preserve the essence.",
        text: "Sustainable craftsmanship and an identity connected to nature.",
      },
      {
        step: "02 · BUILD",
        title: "Give the brand shape.",
        text: "Positioning, narrative, content, and digital experience, aligned.",
      },
      {
        step: "03 · EXPANSION",
        title: "Cross borders.",
        text: "A bilingual site and communication built for two markets.",
      },
    ],
    visualBrandLabel: "BRAND / ORIGIN",
    visualSiteLabel: "SITE / INTERNATIONALIZATION",
    creditsAriaLabel: "Work VIA delivered for Moikato",
    deliveries: [
      { number: "01", title: "Positioning" },
      { number: "02", title: "Brand" },
      { number: "03", title: "Narrative" },
      { number: "04", title: "Content" },
      { number: "05", title: "Bilingual site" },
      { number: "06", title: "Internationalization" },
    ],
  },

  finalCta: {
    kicker: "NEXT MOVE",
    titleLine1: "Let's build",
    titleLine2Lead: "what ",
    titleLine2Highlight: "comes next.",
    description: "Digital solutions in strategy, creativity, and technology.",
    ctaNote: "Have a project in mind?",
    ctaLabel: "Talk to VIA",
    emailPrompt: "Prefer email?",
  },

  footer: {
    logoLabel: "VIA, back to top",
    tagline: "growth company",
    contactAriaLabel: "Contact",
    whatsappLabel: "WhatsApp",
    copyright: "© 2026 VIA. Growth in motion.",
  },

  contact: {
    whatsappMessage: "Hi, I found VIA's work and I'd like to talk about a project.",
  },

  caseProjects: [
    {
      id: "case-moikato",
      name: "Moikato",
      label: "01 / INTERNATIONAL BRAND",
      tags: "BRAND · POSITIONING · DIGITAL",
      description:
        "A brand universe rooted in nature, built to go international.",
      image: "/projects/moikato-brand.webp",
      alt: "Visual identity applied to Moikato's brand",
      fit: "cover",
      position: "center",
      surface: "moikato",
      href: "https://moikato.com",
      cta: "View project",
    },
    {
      id: "case-tardinha",
      name: "A Tardinha",
      label: "02 / LANDING PAGE",
      tags: "LANDING PAGE · TICKETS · EXPERIENCE",
      description: "Landing pages built to sell event tickets.",
      image: "/projects/hero/tardinha-cinematic.webp",
      alt: "Sunset experience featured in the A Tardinha project",
      fit: "cover",
      position: "center",
      surface: "tardinha",
      href: "https://xn--tardinhariosolimes-82b.com/",
      cta: "Visit site",
    },
    {
      id: "case-saude",
      name: "Healthcare clinics",
      label: "03 / DIGITAL ACQUISITION",
      tags: "STRATEGY · CONTENT · TRAFFIC",
      description:
        "Digital strategy and communication for healthcare professionals.",
      kind: "health",
      surface: "health",
      alt: "Digital composition representing VIA's work with clinics",
    },
    {
      id: "case-in-tha-route",
      name: "In Tha Route",
      label: "04 / VISUAL IDENTITY",
      tags: "REBRANDING · BRAND · DIRECTION",
      description: "An old brand transformed into an identity ready for a new chapter.",
      image: "/projects/route-primary.webp",
      alt: "In Tha Route's new identity, created by VIA",
      fit: "contain",
      position: "center",
      surface: "route",
      compare: {
        before: {
          src: "/projects/route-before.webp",
          alt: "In Tha Kitchen's old identity, crossed knives inside a red circle",
        },
        after: {
          src: "/projects/route-primary.webp",
          alt: "In Tha Route's new identity, created by VIA",
        },
        ariaLabel: "Compare In Tha Route's old and new identity",
        caption:
          "Drag the handle or use the arrow keys to compare the brand's before and after.",
      },
    },
    {
      id: "case-conteudo-visual",
      name: "Visual content",
      label: "05 / FLYERS & ARTWORK",
      tags: "CAMPAIGNS · EVENTS · SOCIAL",
      description:
        "Flyers, promotional pieces, and campaigns for brands and events.",
      image: "/projects/latino-beats.webp",
      alt: "Latino Beats flyer created for an event in London",
      kind: "content",
      surface: "content",
      collage: [
        {
          src: "/projects/in-tha-route-flyer-full.webp",
          alt: "In Tha Route promotional flyer",
        },
        {
          src: "/projects/latino-beats.webp",
          alt: "Latino Beats flyer created for an event in London",
        },
        {
          src: "/projects/ghetto-baile-funk.webp",
          alt: "Flyer for the Ghetto Made in Brazil funk party",
        },
      ],
    },
    {
      id: "case-sweet-popcorn",
      name: "Sweet Popcorn Gourmet",
      label: "06 / BRAND & PACKAGING",
      tags: "LOGO · BRANDING · PACKAGING",
      description: "A colorful identity applied to packaging to make the product recognizable.",
      image: "/projects/hero/sweet-popcorn-cinematic.webp",
      alt: "Sweet Popcorn Gourmet packaging featuring the identity created by VIA",
      fit: "cover",
      position: "center",
      surface: "sweet",
    },
    {
      id: "case-sephie-tarot",
      name: "Sephie Tarot",
      label: "07 / LOGO & IDENTITY",
      tags: "LOGO · SYMBOL · SIGNATURE",
      description: "Logo, symbol, and visual signature.",
      image: "/projects/artes/sephie-prancha.webp",
      alt: "Sephie Tarot's visual signature, created by VIA",
      fit: "contain",
      position: "center",
      surface: "sephie",
    },
    {
      id: "case-xango",
      name: "Xangô 7 Cachoeiras",
      label: "08 / BRAND & SYMBOL",
      tags: "LOGO · SYMBOL · IDENTITY",
      description: "A visual signature to give it more identity.",
      image: "/projects/tux7c-primary.webp",
      alt: "Identity for the Xangô 7 Cachoeiras Umbanda temple",
      fit: "contain",
      position: "center",
      surface: "xango",
    },
    {
      id: "case-studio-giu",
      name: "Studio da Giu",
      label: "09 / BRAND & MATERIALS",
      tags: "IDENTITY · GRAPHIC PIECES",
      description: "Visual identity and graphic materials, built from the ground up.",
      image: "/projects/studio-giu-pricing.webp",
      alt: "Price list created for Studio da Giu",
      fit: "contain",
      position: "center",
      surface: "studio",
    },
    {
      id: "case-carolina-carvalho",
      name: "Carolina Carvalho",
      label: "10 / REBRANDING",
      tags: "BRAND · PALETTE · GUIDELINES",
      description: "Rebranding, palette, and brand guidelines for a podiatrist.",
      image: "/projects/carolina-depois.webp",
      alt: "Carolina Carvalho's new brand, created by VIA",
      fit: "contain",
      position: "center",
      surface: "carolina",
      compare: {
        before: {
          src: "/projects/carolina-antes.webp",
          alt: "Podiatrist Carolina Carvalho's old brand",
        },
        after: {
          src: "/projects/carolina-depois.webp",
          alt: "Carolina Carvalho's new brand, created by VIA",
        },
        ariaLabel: "Compare Carolina Carvalho's old and new brand",
        caption:
          "Drag the handle or use the arrow keys to compare the brand's before and after.",
      },
    },
  ],
};
