export const pt = {
  locale: "pt-BR",
  htmlLang: "pt-BR",
  path: "/",

  meta: {
    title: "VIA — Estratégia que ganha forma",
    description:
      "Estratégia, marca, marketing, comercial e tecnologia conectados para construir negócios em movimento.",
    ogImageAlt: "VIA — estratégia que ganha forma.",
  },

  skipLinkLabel: "Ir para o conteúdo",

  organization: {
    availableLanguage: ["pt-BR"],
  },

  header: {
    logoLabel: "VIA, início",
    navAriaLabel: "Navegação principal",
    navCompactAriaLabel: "Navegação principal, versão compacta",
    nav: [
      { id: "fazemos", label: "O que fazemos" },
      { id: "moikato", label: "Moikato" },
      { id: "trabalhos", label: "Trabalhos" },
      { id: "contato", label: "Contato" },
    ],
    ctaLabel: "Fale com a VIA",
    menuAriaLabel: "Menu",
    openMenuLabel: "Abrir menu",
    closeMenuLabel: "Fechar menu",
    menuContactNote: "Tem um projeto em mente?",
    menuContactLabel: "Fale com a VIA",
    langSwitch: {
      label: "EN",
      href: "/en",
      ariaLabel: "Ver o site em inglês",
    },
  },

  hero: {
    kicker: "VIA / GROWTH COMPANY",
    headlineAriaLabel: "VIA — estratégia que ganha forma.",
    headlineLead: "Estratégia que ",
    headlineHighlight: "ganha forma.",
    ctaNote: "Tem um projeto em mente?",
    ctaLabel: "Vamos conversar",
    secondaryCtaLabel: "Conheça a VIA",
  },

  coverflow: {
    assistiveTitle: "Projetos que ganharam forma.",
    regionRoleDescription: "carrossel",
    regionLabel: "Projetos da VIA",
    prevLabel: "Projeto anterior",
    nextLabel: "Próximo projeto",
    selectLabelPrefix: "Selecionar projeto",
    slideLabelProjectWord: "Projeto",
    slideLabelOfWord: "de",
    byVia: "PROJETO VIA",
    gestureHint: "Deslize, use o scroll lateral ou as setas.",
    beforeAfter: {
      beforeLabel: "Antes",
      afterLabel: "Depois",
      valueTextSuffix: "da nova identidade visível",
    },
    health: {
      statement: "Cuidado que transforma vidas.",
      disciplines: ["Estratégia", "Conteúdo", "Mídia"],
      alertLabel: "Novo agendamento",
      ticketTitle: "Consulta confirmada",
      ticketMeta: "Vitae · Cardiologia",
      ticketDay: "Terça, 14h",
      ticketMode: "Presencial",
    },
  },

  capabilities: {
    kicker: "DA IDEIA À OPERAÇÃO",
    title: "A VIA pensa e faz.",
    description:
      "Estratégia e execução caminham juntas para transformar ideias em marcas, experiências e crescimento real.",
    previewAriaPrefix: "Ver",
    previewAriaMiddle: "como exemplo de",
    items: [
      {
        accent: "purple",
        icon: "marca",
        title: "Marca & identidade",
        text: "Posicionamento, naming, logo e um sistema visual que sustenta a marca.",
        reference: {
          client: "In Tha Route",
          href: "#case-in-tha-route",
          image: "/projects/route-primary.webp",
          position: "right center",
          fit: "contain",
        },
      },
      {
        accent: "blue",
        icon: "site",
        title: "Sites & landing pages",
        text: "Experiências digitais para apresentar, conduzir e converter.",
        reference: {
          client: "A Tardinha",
          href: "#case-tardinha",
          image: "/tardinha.webp",
          position: "center",
          fit: "contain",
        },
      },
      {
        accent: "cyan",
        icon: "conteudo",
        title: "Conteúdo & campanhas",
        text: "Social media, gestão de redes, roteiros e campanhas com direção criativa.",
        reference: {
          client: "Conteúdo visual",
          href: "#case-conteudo-visual",
          image: "/projects/latino-beats.webp",
          position: "center 34%",
        },
      },
      {
        accent: "green",
        icon: "trafego",
        title: "Tráfego & performance",
        text: "Crescimento orgânico e pago com leitura, aprendizado e próxima ação.",
        reference: {
          client: "Clínicas na área da saúde",
          href: "#case-saude",
        },
      },
      {
        accent: "blue",
        icon: "estrategia",
        title: "Estratégia & comercial",
        text: "Oferta e processo conectados para aproximar demanda de receita.",
        reference: {
          client: "Moikato",
          href: "#case-moikato",
          image: "/projects/moikato-brand.webp",
          position: "center",
          fit: "contain",
        },
      },
      {
        accent: "cyan",
        icon: "tecnologia",
        title: "Tecnologia & automação",
        text: "Sites, CRM, automações e IA aplicados ao negócio.",
        reference: {
          client: "Moikato",
          href: "#case-moikato",
          image: "/via-moikato-london.webp",
          position: "center 38%",
        },
      },
    ],
  },

  system: {
    videoAriaLabel: "Depoimento em vídeo de Samuel, da Moikato, sobre o trabalho da VIA",
    videoFallback: "Seu navegador não consegue reproduzir este vídeo.",
    videoBadge: "DEPOIMENTO REAL · LONDRES",
    quoteKicker: "RESULTADO EM PRIMEIRA PESSOA",
    quote: "“Eles acreditaram no meu trabalho.”",
    quoteAttribution: "Samuel · Moikato · Empresário em Londres",
    caseKicker: "CASE / MOIKATO / BRASIL → REINO UNIDO",
    title: "Uma história brasileira, contada por quem a vive.",
    description:
      "A Moikato cresceu do Brasil para o Reino Unido. A VIA conectou origem, marca e experiência digital para acompanhar esse movimento.",
    storyAriaLabel: "A história do projeto em três momentos",
    story: [
      {
        step: "01 · ORIGEM",
        title: "Preservar a essência.",
        text: "Artesanato sustentável e uma identidade conectada à natureza.",
      },
      {
        step: "02 · CONSTRUÇÃO",
        title: "Dar forma à marca.",
        text: "Posicionamento, narrativa, conteúdo e experiência digital alinhados.",
      },
      {
        step: "03 · EXPANSÃO",
        title: "Atravessar fronteiras.",
        text: "Um site bilíngue e uma comunicação preparados para dois mercados.",
      },
    ],
    visualBrandLabel: "MARCA / ORIGEM",
    visualSiteLabel: "SITE / INTERNACIONALIZAÇÃO",
    creditsAriaLabel: "Entregas realizadas pela VIA para a Moikato",
    deliveries: [
      { number: "01", title: "Posicionamento" },
      { number: "02", title: "Marca" },
      { number: "03", title: "Narrativa" },
      { number: "04", title: "Conteúdo" },
      { number: "05", title: "Site bilíngue" },
      { number: "06", title: "Internacionalização" },
    ],
  },

  finalCta: {
    kicker: "PRÓXIMO MOVIMENTO",
    titleLine1: "Vamos construir",
    titleLine2Lead: "o que ",
    titleLine2Highlight: "vem a seguir.",
    description: "Soluções digitais de estratégia, criatividade e tecnologia.",
    ctaNote: "Tem um projeto em mente?",
    ctaLabel: "Fale com a VIA",
    emailPrompt: "Prefere e-mail?",
  },

  footer: {
    logoLabel: "VIA, voltar ao início",
    tagline: "growth company",
    contactAriaLabel: "Contato",
    whatsappLabel: "WhatsApp",
    copyright: "© 2026 VIA. Crescimento em movimento.",
  },

  contact: {
    whatsappMessage: "Olá, conheci o trabalho da VIA e quero conversar sobre um projeto.",
  },

  caseProjects: [
    {
      id: "case-moikato",
      name: "Moikato",
      label: "01 / MARCA INTERNACIONAL",
      tags: "MARCA · POSICIONAMENTO · DIGITAL",
      description:
        "Um universo de marca enraizado na natureza e preparado para ganhar presença internacional.",
      image: "/projects/moikato-brand.webp",
      alt: "Aplicação da identidade visual criada para a Moikato",
      fit: "cover",
      position: "center",
      surface: "moikato",
      href: "https://moikato.com",
      cta: "Ver projeto",
    },
    {
      id: "case-tardinha",
      name: "A Tardinha",
      label: "02 / LANDING PAGE",
      tags: "LANDING PAGE · INGRESSOS · EXPERIÊNCIA",
      description: "Criação de landing pages para venda de ingressos.",
      image: "/projects/hero/tardinha-cinematic.webp",
      alt: "Experiência ao pôr do sol apresentada no projeto A Tardinha",
      fit: "cover",
      position: "center",
      surface: "tardinha",
      href: "https://xn--tardinhariosolimes-82b.com/",
      cta: "Visitar site",
    },
    {
      id: "case-saude",
      name: "Clínicas na área da saúde",
      label: "03 / AQUISIÇÃO DIGITAL",
      tags: "ESTRATÉGIA · CONTEÚDO · TRÁFEGO",
      description:
        "Estratégia digital e comunicação para profissionais da área da saúde.",
      kind: "health",
      surface: "health",
      alt: "Composição digital criada para representar o trabalho da VIA com clínicas",
    },
    {
      id: "case-in-tha-route",
      name: "In Tha Route",
      label: "04 / IDENTIDADE VISUAL",
      tags: "REBRANDING · MARCA · DIREÇÃO",
      description: "Uma marca antiga transformada em uma identidade preparada para um novo momento.",
      image: "/projects/route-primary.webp",
      alt: "Nova identidade da In Tha Route criada pela VIA",
      fit: "contain",
      position: "center",
      surface: "route",
      compare: {
        before: {
          src: "/projects/route-before.webp",
          alt: "Identidade antiga da In Tha Kitchen, com facas cruzadas em um círculo vermelho",
        },
        after: {
          src: "/projects/route-primary.webp",
          alt: "Nova identidade da In Tha Route criada pela VIA",
        },
        ariaLabel: "Comparar a identidade antiga e a nova da In Tha Route",
        caption:
          "Arraste o controle ou use as setas do teclado para comparar o antes e o depois da marca.",
      },
    },
    {
      id: "case-conteudo-visual",
      name: "Conteúdo visual",
      label: "05 / PANFLETOS & PEÇAS",
      tags: "CAMPANHAS · EVENTOS · SOCIAL",
      description:
        "Panfletos, peças promocionais e campanhas para marcas e eventos.",
      image: "/projects/latino-beats.webp",
      alt: "Panfleto Latino Beats criado para evento em Londres",
      kind: "content",
      surface: "content",
      collage: [
        {
          src: "/projects/in-tha-route-flyer-full.webp",
          alt: "Panfleto promocional da In Tha Route",
        },
        {
          src: "/projects/latino-beats.webp",
          alt: "Panfleto Latino Beats criado para evento em Londres",
        },
        {
          src: "/projects/ghetto-baile-funk.webp",
          alt: "Panfleto do baile funk Ghetto Made in Brazil",
        },
      ],
    },
    {
      id: "case-sweet-popcorn",
      name: "Sweet Popcorn Gourmet",
      label: "06 / MARCA & EMBALAGEM",
      tags: "LOGO · BRANDING · EMBALAGEM",
      description: "Identidade colorida aplicada à embalagem para tornar o produto reconhecível.",
      image: "/projects/hero/sweet-popcorn-cinematic.webp",
      alt: "Embalagem da Sweet Popcorn Gourmet com a identidade criada pela VIA",
      fit: "cover",
      position: "center",
      surface: "sweet",
    },
    {
      id: "case-sephie-tarot",
      name: "Sephie Tarot",
      label: "07 / LOGO & IDENTIDADE",
      tags: "LOGO · SÍMBOLO · ASSINATURA",
      description: "Logo, símbolo e assinatura visual.",
      image: "/projects/artes/sephie-prancha.webp",
      alt: "Assinatura visual da Sephie Tarot criada pela VIA",
      fit: "contain",
      position: "center",
      surface: "sephie",
    },
    {
      id: "case-xango",
      name: "Xangô 7 Cachoeiras",
      label: "08 / MARCA & SÍMBOLO",
      tags: "LOGO · SÍMBOLO · IDENTIDADE",
      description: "Assinatura visual para trazer mais identidade.",
      image: "/projects/tux7c-primary.webp",
      alt: "Identidade do Terreiro de Umbanda Xangô 7 Cachoeiras",
      fit: "contain",
      position: "center",
      surface: "xango",
    },
    {
      id: "case-studio-giu",
      name: "Studio da Giu",
      label: "09 / MARCA & MATERIAIS",
      tags: "IDENTIDADE · PEÇAS GRÁFICAS",
      description: "Construção de identidade visual e materiais gráficos.",
      image: "/projects/studio-giu-pricing.webp",
      alt: "Tabela de preços criada para o Studio da Giu",
      fit: "contain",
      position: "center",
      surface: "studio",
    },
    {
      id: "case-carolina-carvalho",
      name: "Carolina Carvalho",
      label: "10 / REBRANDING",
      tags: "MARCA · PALETA · MANUAL",
      description: "Rebranding, paleta e manual de marca para podóloga.",
      image: "/projects/carolina-depois.webp",
      alt: "Nova marca de Carolina Carvalho criada pela VIA",
      fit: "contain",
      position: "center",
      surface: "carolina",
      compare: {
        before: {
          src: "/projects/carolina-antes.webp",
          alt: "Marca antiga da podóloga Carolina Carvalho",
        },
        after: {
          src: "/projects/carolina-depois.webp",
          alt: "Nova marca de Carolina Carvalho criada pela VIA",
        },
        ariaLabel: "Comparar a marca antiga e a nova de Carolina Carvalho",
        caption:
          "Arraste o controle ou use as setas do teclado para comparar o antes e o depois da marca.",
      },
    },
  ],
};
