/*
 * A hero funciona como uma constelação de trabalhos, não como uma grade de
 * cards. Cada peça ocupa um dos três planos de profundidade e conserva a
 * proporção do material original: página, cartaz, símbolo ou embalagem.
 *
 * Os planos inteiros recebem o parallax. Isso mantém a sensação de espaço sem
 * recalcular o movimento de cada imagem a cada evento do ponteiro.
 */
export const heroProjectLayers = [
  {
    id: "far",
    projects: [
      {
        id: "ana-paula",
        title: "Ana Paula",
        type: "Identidade visual",
        line: "Marca para organização profissional",
        href: "#trabalhos",
        src: "/projects/ana-paula-organizer.webp",
        alt: "Identidade visual de Ana Paula Personal Organizer",
        slot: "projectAnaPaula",
        surface: "surfaceLight",
        fit: "contain",
      },
      {
        id: "carolina",
        title: "Carolina Carvalho",
        type: "Rebranding",
        line: "Paleta e assinatura visual",
        href: "#case-carolina-carvalho",
        src: "/projects/carolina-depois.webp",
        alt: "Nova identidade visual de Carolina Carvalho",
        slot: "projectCarolina",
        surface: "surfacePurple",
      },
      {
        id: "sephie-symbol",
        title: "Sephie Tarot",
        type: "Símbolo",
        line: "Beleza que transcende",
        href: "#trabalhos",
        src: "/projects/sephie-tarot-symbol.webp",
        alt: "Símbolo em forma de lua criado para Sephie Tarot",
        slot: "projectSephieSymbol",
        surface: "surfaceLight",
        fit: "contain",
      },
      {
        id: "route-symbol",
        title: "In Tha Route",
        type: "Identidade",
        line: "Logística com direção de marca",
        href: "#case-in-tha-route",
        src: "/projects/route-primary.webp",
        alt: "Assinatura visual da In Tha Route",
        slot: "projectRouteSymbol",
        surface: "surfacePurple",
        fit: "contain",
      },
      {
        id: "ghetto",
        title: "Ghetto Baile Funk",
        type: "Conteúdo visual",
        line: "Cartaz promocional para evento",
        href: "#case-conteudo-visual",
        src: "/projects/ghetto-baile-funk.webp",
        alt: "Cartaz do evento Ghetto Baile Funk",
        slot: "projectGhetto",
        surface: "surfaceDark",
      },
    ],
  },
  {
    id: "mid",
    projects: [
      {
        id: "tardinha-scene",
        title: "A Tardinha",
        type: "Landing page",
        line: "O melhor fim de tarde da sua vida",
        href: "#case-tardinha",
        src: "/projects/artes/tardinha-cena.webp",
        alt: "Cena do pôr do sol criada para A Tardinha",
        slot: "projectTardinhaScene",
        surface: "surfaceWarm",
        priority: true,
      },
      {
        id: "route-flyer",
        title: "In Tha Route",
        type: "Campanha",
        line: "Conteúdo visual para aquisição",
        href: "#case-in-tha-route",
        src: "/projects/in-tha-route-flyer-full.webp",
        alt: "Panfleto promocional da In Tha Route",
        slot: "projectRouteFlyer",
        surface: "surfaceDark",
        position: "center top",
      },
      {
        id: "studio-giu",
        title: "Studio da Giu",
        type: "Marca & materiais",
        line: "Identidade para nail e lash designer",
        href: "#trabalhos",
        src: "/projects/studio-giu-pricing.webp",
        alt: "Tabela de preços desenvolvida para o Studio da Giu",
        slot: "projectStudioGiu",
        surface: "surfaceLight",
      },
      {
        id: "latino-beats",
        title: "Latino Beats",
        type: "Conteúdo visual",
        line: "Panfletos e campanhas para eventos",
        href: "#case-conteudo-visual",
        src: "/projects/latino-beats.webp",
        alt: "Cartaz promocional do evento Latino Beats",
        slot: "projectLatino",
        surface: "surfaceNeon",
        position: "center 18%",
      },
      {
        id: "xango",
        title: "Xangô 7 Cachoeiras",
        type: "Marca & símbolo",
        line: "Logo, símbolo e assinatura visual",
        href: "#trabalhos",
        src: "/projects/tux7c-primary.webp",
        alt: "Prancha da identidade de Xangô 7 Cachoeiras",
        slot: "projectXango",
        surface: "surfaceCream",
        fit: "contain",
      },
    ],
  },
  {
    id: "near",
    projects: [
      {
        id: "moikato",
        title: "Moikato",
        type: "Marca & internacionalização",
        line: "Brazil meets Europe",
        href: "https://moikato.com",
        external: true,
        src: "/projects/moikato-brand.webp",
        alt: "Marca Moikato aplicada em uma parede com luz natural",
        slot: "projectMoikato",
        surface: "surfaceMoikato",
        priority: true,
      },
      {
        id: "sephie",
        title: "Sephie Tarot",
        type: "Identidade visual",
        line: "Beleza que transcende",
        href: "#trabalhos",
        src: "/projects/artes/sephie-prancha.webp",
        alt: "Prancha horizontal da assinatura visual criada para Sephie Tarot",
        slot: "projectSephie",
        surface: "surfaceLight",
      },
      {
        id: "sweet-popcorn",
        title: "Sweet Popcorn Gourmet",
        type: "Marca & embalagem",
        line: "Estourado com ingredientes reais",
        href: "#trabalhos",
        src: "/projects/sweet-popcorn-gourmet.webp",
        alt: "Embalagem colorida da Sweet Popcorn Gourmet",
        slot: "projectSweet",
        surface: "surfaceWhite",
        fit: "contain",
        priority: true,
      },
      {
        id: "tardinha-mark",
        title: "A Tardinha",
        type: "Experiência digital",
        line: "Landing page para venda de ingressos",
        href: "#case-tardinha",
        src: "/tardinha.webp",
        alt: "Símbolo de A Tardinha da Rio Solimões",
        slot: "projectTardinhaMark",
        surface: "surfaceCutout",
        fit: "contain",
      },
    ],
  },
];
