/*
 * O hero é um trilho de projetos, igual em qualquer largura. A ordem do array
 * é a ordem do carrossel: as peças que definem a marca abrem, as marcas de
 * apoio fecham. Cada projeto carrega a própria proporção via CSS (--ratio),
 * então o card preserva o enquadramento original da arte.
 */
export const heroProjects = [
  {
    id: "sweet-popcorn",
    title: "Sweet Popcorn Gourmet",
    type: "Marca & embalagem",
    line: "Estourado com ingredientes reais",
    href: "#trabalhos",
    src: "/projects/recortes/sweet-popcorn.webp",
    alt: "Embalagem da Sweet Popcorn Gourmet com pipocas coloridas",
    slot: "projectSweetCutout",
    surface: "surfaceCutout",
    fit: "contain",
    sizes: "(max-width: 1000px) 46vw, 22vw",
  },
  {
    id: "moikato-board",
    title: "Moikato",
    type: "Marca & internacionalização",
    line: "Brazil meets Europe",
    href: "https://moikato.com",
    external: true,
    src: "/projects/moikato-brand.webp",
    alt: "Direção de marca desenvolvida para Moikato",
    slot: "projectMoikatoBoard",
    surface: "surfaceDark",
    visual: "moikatoBoard",
    preload: true,
  },
  {
    id: "sephie-board",
    title: "Sephie Tarot",
    type: "Identidade visual",
    line: "Beleza que transcende",
    href: "#trabalhos",
    src: "/projects/sephie-tarot-signature.webp",
    alt: "Identidade visual criada para Sephie Tarot",
    slot: "projectSephieBoard",
    surface: "surfaceDark",
    visual: "sephieBoard",
  },
  {
    id: "tardinha-scene",
    title: "A Tardinha",
    type: "Landing page",
    line: "O melhor fim de tarde da sua vida",
    href: "#case-tardinha",
    src: "/projects/artes/tardinha-cena.webp",
    alt: "Cena do pôr do sol criada para A Tardinha",
    slot: "projectTardinhaScene",
    surface: "surfaceWarm",
  },
  {
    id: "health-phone",
    title: "Clínicas na área da saúde",
    type: "Estratégia digital",
    line: "Comunicação e aquisição para profissionais da saúde",
    href: "#trabalhos",
    slot: "projectHealthPhone",
    surface: "surfaceLight",
    visual: "healthPhone",
  },
  {
    id: "route-board",
    title: "In Tha Route",
    type: "Campanha",
    line: "Conteúdo visual para aquisição",
    href: "#case-in-tha-route",
    src: "/projects/in-tha-route-flyer-full.webp",
    alt: "Panfleto promocional da In Tha Route",
    slot: "projectRouteBoard",
    surface: "surfaceDark",
    visual: "routeBoard",
  },
  {
    id: "xango",
    title: "Xangô 7 Cachoeiras",
    type: "Marca & símbolo",
    line: "Logo, símbolo e assinatura visual",
    href: "#trabalhos",
    src: "/projects/tux7c-primary.webp",
    alt: "Prancha da identidade de Xangô 7 Cachoeiras",
    slot: "projectXango",
    surface: "surfaceCream",
    fit: "contain",
  },
  {
    id: "latino-beats",
    title: "Latino Beats",
    type: "Conteúdo visual",
    line: "Panfletos e campanhas para eventos",
    href: "#case-conteudo-visual",
    src: "/projects/latino-beats.webp",
    alt: "Cartaz promocional do evento Latino Beats",
    slot: "projectLatino",
    surface: "surfaceNeon",
    position: "center 18%",
  },
  {
    id: "carolina-board",
    title: "Carolina Carvalho",
    type: "Rebranding",
    line: "Beleza, essência, presença",
    href: "#case-carolina-carvalho",
    src: "/projects/carolina-depois.webp",
    alt: "Nova identidade visual de Carolina Carvalho",
    slot: "projectCarolinaBoard",
    surface: "surfaceDark",
    visual: "carolinaBoard",
  },
  {
    id: "ana-paula",
    title: "Ana Paula",
    type: "Identidade visual",
    line: "Marca para organização profissional",
    href: "#trabalhos",
    src: "/projects/ana-paula-organizer.webp",
    alt: "Identidade visual de Ana Paula Personal Organizer",
    slot: "projectAnaPaula",
    surface: "surfaceLight",
    fit: "contain",
  },
  {
    id: "studio-giu",
    title: "Studio da Giu",
    type: "Marca & materiais",
    line: "Identidade para nail e lash designer",
    href: "#trabalhos",
    src: "/projects/studio-giu-pricing.webp",
    alt: "Tabela de preços desenvolvida para o Studio da Giu",
    slot: "projectStudioGiuFar",
    surface: "surfaceLight",
  },
  {
    id: "ghetto",
    title: "Ghetto Baile Funk",
    type: "Conteúdo visual",
    line: "Cartaz promocional para evento",
    href: "#case-conteudo-visual",
    src: "/projects/ghetto-baile-funk.webp",
    alt: "Cartaz do evento Ghetto Baile Funk",
    slot: "projectGhetto",
    surface: "surfaceDark",
  },
  {
    id: "route-symbol",
    title: "In Tha Route",
    type: "Identidade",
    line: "Logística com direção de marca",
    href: "#case-in-tha-route",
    src: "/projects/route-primary.webp",
    alt: "Assinatura visual da In Tha Route",
    slot: "projectRouteSymbol",
    surface: "surfacePurple",
    fit: "contain",
  },
];
